//! C ABI over the Rocq-extracted algorithms, for `ctypes` and friends.
//!
//! `src/sorting.rs` and `src/trading.rs` are generated by the Makefile:
//! extracted Rocq output plus a small `pub` API suffix. Each keeps its own
//! `Program`, arena and datatypes, so they live in separate modules -- the
//! generated code declares identically-named types in both.
//!
//! Conventions:
//!   - every function returns a status code; results come back via `*mut`
//!     out-parameters, so failure is distinguishable from a valid result
//!   - a zero `len` is always valid, whatever the pointer is
//!   - unwinding is caught at the boundary, never allowed to cross it

mod modexp;
mod order_fsm;
mod rle;
mod sorting;
mod trading;
/// Same Rocq source, extracted with `ExtrRustCheckedArith`: every `Z`
/// operation becomes `checked_*().unwrap()`, so i64 overflow panics instead
/// of wrapping silently. `catch_unwind` below turns that into `ROCQ_ERR_PANIC`.
mod trading_checked;

use std::panic::{catch_unwind, AssertUnwindSafe};
use std::slice;

pub const ROCQ_OK: i32 = 0;
/// A required pointer was null (with a non-zero length).
pub const ROCQ_ERR_NULL: i32 = -1;
/// The extracted code panicked; the panic was contained.
pub const ROCQ_ERR_PANIC: i32 = -2;

/// # Safety
/// `ptr` must be valid for `len` reads of `T`, or `len` must be 0.
unsafe fn as_slice<'a, T>(ptr: *const T, len: usize) -> Option<&'a [T]> {
    if len == 0 {
        Some(&[])
    } else if ptr.is_null() {
        None
    } else {
        Some(slice::from_raw_parts(ptr, len))
    }
}

/// A library should not write to the caller's stderr. Overflow in the
/// checked build is reported through the return code; set `ROCQ_FFI_VERBOSE`
/// to get Rust's default panic message back for debugging.
fn quiet_panics() {
    use std::sync::Once;
    static ONCE: Once = Once::new();
    ONCE.call_once(|| {
        if std::env::var_os("ROCQ_FFI_VERBOSE").is_none() {
            let default = std::panic::take_hook();
            std::panic::set_hook(Box::new(move |info| {
                if std::env::var_os("ROCQ_FFI_VERBOSE").is_some() {
                    default(info);
                }
            }));
        }
    });
}

fn guard<F: FnOnce() -> i64>(f: F, out: *mut i64) -> i32 {
    quiet_panics();
    if out.is_null() {
        return ROCQ_ERR_NULL;
    }
    match catch_unwind(AssertUnwindSafe(f)) {
        Ok(v) => {
            unsafe { *out = v };
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}

/// Sort `len` values from `input` into `out`, which must have room for `len`.
///
/// # Safety
/// `input` and `out` must each be valid for `len` elements.
#[no_mangle]
pub unsafe extern "C" fn rocq_sort_i64(input: *const i64, len: usize, out: *mut i64) -> i32 {
    let Some(xs) = as_slice(input, len) else {
        return ROCQ_ERR_NULL;
    };
    if len > 0 && out.is_null() {
        return ROCQ_ERR_NULL;
    }
    quiet_panics();
    match catch_unwind(AssertUnwindSafe(|| sorting::sort(xs))) {
        Ok(v) => {
            // v.len() == len is the `insertion_sort_length` theorem, but the
            // FFI boundary does not get to assume Rocq theorems about code it
            // was handed -- clamp anyway.
            let n = v.len().min(len);
            if n > 0 {
                std::ptr::copy_nonoverlapping(v.as_ptr(), out, n);
            }
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}

/// # Safety
/// `px` must be valid for `len` elements; `out` must be a valid `*mut i64`.
#[no_mangle]
pub unsafe extern "C" fn rocq_max_profit(px: *const i64, len: usize, out: *mut i64) -> i32 {
    let Some(xs) = as_slice(px, len) else {
        return ROCQ_ERR_NULL;
    };
    guard(|| trading::max_profit(xs), out)
}

/// Overflow-checked `max_profit`: returns `ROCQ_ERR_PANIC` rather than a
/// wrong answer when an intermediate leaves i64.
///
/// # Safety
/// `px` must be valid for `len` elements; `out` must be a valid `*mut i64`.
#[no_mangle]
pub unsafe extern "C" fn rocq_max_profit_checked(
    px: *const i64,
    len: usize,
    out: *mut i64,
) -> i32 {
    let Some(xs) = as_slice(px, len) else {
        return ROCQ_ERR_NULL;
    };
    guard(|| trading_checked::max_profit(xs), out)
}

/// Overflow-checked `max_drawdown`.
///
/// # Safety
/// `px` must be valid for `len` elements; `out` must be a valid `*mut i64`.
#[no_mangle]
pub unsafe extern "C" fn rocq_max_drawdown_checked(
    px: *const i64,
    len: usize,
    out: *mut i64,
) -> i32 {
    let Some(xs) = as_slice(px, len) else {
        return ROCQ_ERR_NULL;
    };
    guard(|| trading_checked::max_drawdown(xs), out)
}

/// Overflow-checked risk gate.
///
/// # Safety
/// `sides` and `qtys` must each be valid for `len` elements.
#[no_mangle]
pub unsafe extern "C" fn rocq_run_orders_checked(
    limit: i64,
    initial: i64,
    sides: *const u8,
    qtys: *const i64,
    len: usize,
    out: *mut i64,
) -> i32 {
    let (Some(s), Some(q)) = (as_slice(sides, len), as_slice(qtys, len)) else {
        return ROCQ_ERR_NULL;
    };
    let os: Vec<(bool, i64)> = s.iter().zip(q).map(|(&b, &n)| (b != 0, n)).collect();
    guard(|| trading_checked::run_orders(limit, initial, &os), out)
}

/// # Safety
/// `px` must be valid for `len` elements; `out` must be a valid `*mut i64`.
#[no_mangle]
pub unsafe extern "C" fn rocq_max_drawdown(px: *const i64, len: usize, out: *mut i64) -> i32 {
    let Some(xs) = as_slice(px, len) else {
        return ROCQ_ERR_NULL;
    };
    guard(|| trading::max_drawdown(xs), out)
}

/// Orders are two parallel arrays: `sides[i] != 0` means buy.
///
/// # Safety
/// `sides` and `qtys` must each be valid for `len` elements.
#[no_mangle]
pub unsafe extern "C" fn rocq_run_orders(
    limit: i64,
    initial: i64,
    sides: *const u8,
    qtys: *const i64,
    len: usize,
    out: *mut i64,
) -> i32 {
    let (Some(s), Some(q)) = (as_slice(sides, len), as_slice(qtys, len)) else {
        return ROCQ_ERR_NULL;
    };
    let os: Vec<(bool, i64)> = s.iter().zip(q).map(|(&b, &n)| (b != 0, n)).collect();
    guard(|| trading::run_orders(limit, initial, &os), out)
}

/// All three analytics in one call. `out` must have room for 3 `i64`s:
/// `[max_profit, max_drawdown, final_position]`.
///
/// # Safety
/// `px`/`sides`/`qtys` must be valid for their lengths; `out` for 3 elements.
#[no_mangle]
pub unsafe extern "C" fn rocq_analyze(
    px: *const i64,
    px_len: usize,
    limit: i64,
    sides: *const u8,
    qtys: *const i64,
    os_len: usize,
    out: *mut i64,
) -> i32 {
    let Some(xs) = as_slice(px, px_len) else {
        return ROCQ_ERR_NULL;
    };
    let (Some(s), Some(q)) = (as_slice(sides, os_len), as_slice(qtys, os_len)) else {
        return ROCQ_ERR_NULL;
    };
    if out.is_null() {
        return ROCQ_ERR_NULL;
    }
    let os: Vec<(bool, i64)> = s.iter().zip(q).map(|(&b, &n)| (b != 0, n)).collect();
    quiet_panics();
    match catch_unwind(AssertUnwindSafe(|| trading::analyze(xs, limit, &os))) {
        Ok((profit, dd, pos)) => {
            *out.add(0) = profit;
            *out.add(1) = dd;
            *out.add(2) = pos;
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}

/* ================= RLE codec ================= */

/// Run-length encode `len` values. `out_vals`/`out_counts` must have room
/// for `len` entries — sufficient by `encode_length_le`. Writes the number
/// of runs to `out_n`.
///
/// # Safety
/// `input` valid for `len` reads; `out_vals`/`out_counts` valid for `len`
/// writes; `out_n` a valid pointer.
#[no_mangle]
pub unsafe extern "C" fn rocq_rle_encode(
    input: *const i64,
    len: usize,
    out_vals: *mut i64,
    out_counts: *mut u64,
    out_n: *mut usize,
) -> i32 {
    let Some(xs) = as_slice(input, len) else {
        return ROCQ_ERR_NULL;
    };
    if out_n.is_null() || (len > 0 && (out_vals.is_null() || out_counts.is_null())) {
        return ROCQ_ERR_NULL;
    }
    quiet_panics();
    match catch_unwind(AssertUnwindSafe(|| rle::encode(xs))) {
        Ok(v) => {
            let n = v.len().min(len); // == v.len() by encode_length_le; clamp anyway
            for (i, (val, cnt)) in v.into_iter().take(n).enumerate() {
                *out_vals.add(i) = val;
                *out_counts.add(i) = cnt;
            }
            *out_n = n;
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}

/// Returned by `rocq_rle_decode` when the decoded output exceeds `out_cap`.
pub const ROCQ_ERR_CAPACITY: i32 = -3;

/// Decode `n` (value, count) runs into `out` (capacity `out_cap`); writes
/// the decoded length to `out_len`.
///
/// # Safety
/// `vals`/`counts` valid for `n` reads; `out` valid for `out_cap` writes;
/// `out_len` a valid pointer.
#[no_mangle]
pub unsafe extern "C" fn rocq_rle_decode(
    vals: *const i64,
    counts: *const u64,
    n: usize,
    out: *mut i64,
    out_cap: usize,
    out_len: *mut usize,
) -> i32 {
    let (Some(vs), Some(cs)) = (as_slice(vals, n), as_slice(counts, n)) else {
        return ROCQ_ERR_NULL;
    };
    if out_len.is_null() || (out_cap > 0 && out.is_null()) {
        return ROCQ_ERR_NULL;
    }
    let pairs: Vec<(i64, u64)> = vs.iter().zip(cs).map(|(&v, &c)| (v, c)).collect();
    quiet_panics();
    match catch_unwind(AssertUnwindSafe(|| rle::decode(&pairs))) {
        Ok(v) => {
            if v.len() > out_cap {
                return ROCQ_ERR_CAPACITY;
            }
            if !v.is_empty() {
                std::ptr::copy_nonoverlapping(v.as_ptr(), out, v.len());
            }
            *out_len = v.len();
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}

/* ================= modular exponentiation ================= */

/// `(b ^ e) mod m` (`pow_mod_correct`). Checked build: panics (contained,
/// `ROCQ_ERR_PANIC`) on `m == 0` or intermediates outside u64 — the bindings
/// enforce `1 <= m <= 2^32` (`safe_modulus`) so neither can happen.
///
/// # Safety
/// `out` must be a valid `*mut u64`.
#[no_mangle]
pub unsafe extern "C" fn rocq_pow_mod(m: u64, b: u64, e: u64, out: *mut u64) -> i32 {
    if out.is_null() {
        return ROCQ_ERR_NULL;
    }
    quiet_panics();
    match catch_unwind(AssertUnwindSafe(|| modexp::pow_mod(m, b, e))) {
        Ok(v) => {
            *out = v;
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}

/* ================= order FSM ================= */

/// Run `n` events (`fills[i] != 0` => Fill(qtys[i]), else Cancel) against a
/// fresh order of size `qty`. Writes final fill to `out_filled` and cancel
/// flag to `out_canceled`. Safe for all event streams (`run_invariant`,
/// `fill_add_bounded`); negative/overfilling fills are rejected in-machine.
///
/// # Safety
/// `fills`/`qtys` valid for `n` reads; out pointers valid.
#[no_mangle]
pub unsafe extern "C" fn rocq_order_fsm_run(
    qty: i64,
    fills: *const u8,
    qtys: *const i64,
    n: usize,
    out_filled: *mut i64,
    out_canceled: *mut u8,
) -> i32 {
    let (Some(fs), Some(qs)) = (as_slice(fills, n), as_slice(qtys, n)) else {
        return ROCQ_ERR_NULL;
    };
    if out_filled.is_null() || out_canceled.is_null() {
        return ROCQ_ERR_NULL;
    }
    let evs: Vec<(bool, i64)> = fs.iter().zip(qs).map(|(&f, &q)| (f != 0, q)).collect();
    quiet_panics();
    match catch_unwind(AssertUnwindSafe(|| order_fsm::run(qty, &evs))) {
        Ok((filled, canceled)) => {
            *out_filled = filled;
            *out_canceled = canceled as u8;
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}
