//! C ABI over the Rocq-extracted algorithms, for `ctypes` and friends.
//!
//! `src/sorting.rs` and `src/trading.rs` are generated by the Makefile:
//! extracted Rocq output plus a small `pub` API suffix. Each keeps its own
//! `Program`, arena and datatypes, so they live in separate modules -- the
//! generated code declares identically-named types in both.
//!
//! Conventions:
//!   - every function returns a status code; results come back via `*mut`
//!     out-parameters, so failure is distinguishable from a valid result
//!   - a zero `len` is always valid, whatever the pointer is
//!   - unwinding is caught at the boundary, never allowed to cross it

mod sorting;
mod trading;
/// Same Rocq source, extracted with `ExtrRustCheckedArith`: every `Z`
/// operation becomes `checked_*().unwrap()`, so i64 overflow panics instead
/// of wrapping silently. `catch_unwind` below turns that into `ROCQ_ERR_PANIC`.
mod trading_checked;

use std::panic::{catch_unwind, AssertUnwindSafe};
use std::slice;

pub const ROCQ_OK: i32 = 0;
/// A required pointer was null (with a non-zero length).
pub const ROCQ_ERR_NULL: i32 = -1;
/// The extracted code panicked; the panic was contained.
pub const ROCQ_ERR_PANIC: i32 = -2;

/// # Safety
/// `ptr` must be valid for `len` reads of `T`, or `len` must be 0.
unsafe fn as_slice<'a, T>(ptr: *const T, len: usize) -> Option<&'a [T]> {
    if len == 0 {
        Some(&[])
    } else if ptr.is_null() {
        None
    } else {
        Some(slice::from_raw_parts(ptr, len))
    }
}

/// A library should not write to the caller's stderr. Overflow in the
/// checked build is reported through the return code; set `ROCQ_FFI_VERBOSE`
/// to get Rust's default panic message back for debugging.
fn quiet_panics() {
    use std::sync::Once;
    static ONCE: Once = Once::new();
    ONCE.call_once(|| {
        if std::env::var_os("ROCQ_FFI_VERBOSE").is_none() {
            let default = std::panic::take_hook();
            std::panic::set_hook(Box::new(move |info| {
                if std::env::var_os("ROCQ_FFI_VERBOSE").is_some() {
                    default(info);
                }
            }));
        }
    });
}

fn guard<F: FnOnce() -> i64>(f: F, out: *mut i64) -> i32 {
    quiet_panics();
    if out.is_null() {
        return ROCQ_ERR_NULL;
    }
    match catch_unwind(AssertUnwindSafe(f)) {
        Ok(v) => {
            unsafe { *out = v };
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}

/// Sort `len` values from `input` into `out`, which must have room for `len`.
///
/// # Safety
/// `input` and `out` must each be valid for `len` elements.
#[no_mangle]
pub unsafe extern "C" fn rocq_sort_i64(input: *const i64, len: usize, out: *mut i64) -> i32 {
    let Some(xs) = as_slice(input, len) else {
        return ROCQ_ERR_NULL;
    };
    if len > 0 && out.is_null() {
        return ROCQ_ERR_NULL;
    }
    quiet_panics();
    match catch_unwind(AssertUnwindSafe(|| sorting::sort(xs))) {
        Ok(v) => {
            // v.len() == len is the `insertion_sort_length` theorem, but the
            // FFI boundary does not get to assume Rocq theorems about code it
            // was handed -- clamp anyway.
            let n = v.len().min(len);
            if n > 0 {
                std::ptr::copy_nonoverlapping(v.as_ptr(), out, n);
            }
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}

/// # Safety
/// `px` must be valid for `len` elements; `out` must be a valid `*mut i64`.
#[no_mangle]
pub unsafe extern "C" fn rocq_max_profit(px: *const i64, len: usize, out: *mut i64) -> i32 {
    let Some(xs) = as_slice(px, len) else {
        return ROCQ_ERR_NULL;
    };
    guard(|| trading::max_profit(xs), out)
}

/// Overflow-checked `max_profit`: returns `ROCQ_ERR_PANIC` rather than a
/// wrong answer when an intermediate leaves i64.
///
/// # Safety
/// `px` must be valid for `len` elements; `out` must be a valid `*mut i64`.
#[no_mangle]
pub unsafe extern "C" fn rocq_max_profit_checked(
    px: *const i64,
    len: usize,
    out: *mut i64,
) -> i32 {
    let Some(xs) = as_slice(px, len) else {
        return ROCQ_ERR_NULL;
    };
    guard(|| trading_checked::max_profit(xs), out)
}

/// Overflow-checked `max_drawdown`.
///
/// # Safety
/// `px` must be valid for `len` elements; `out` must be a valid `*mut i64`.
#[no_mangle]
pub unsafe extern "C" fn rocq_max_drawdown_checked(
    px: *const i64,
    len: usize,
    out: *mut i64,
) -> i32 {
    let Some(xs) = as_slice(px, len) else {
        return ROCQ_ERR_NULL;
    };
    guard(|| trading_checked::max_drawdown(xs), out)
}

/// Overflow-checked risk gate.
///
/// # Safety
/// `sides` and `qtys` must each be valid for `len` elements.
#[no_mangle]
pub unsafe extern "C" fn rocq_run_orders_checked(
    limit: i64,
    initial: i64,
    sides: *const u8,
    qtys: *const i64,
    len: usize,
    out: *mut i64,
) -> i32 {
    let (Some(s), Some(q)) = (as_slice(sides, len), as_slice(qtys, len)) else {
        return ROCQ_ERR_NULL;
    };
    let os: Vec<(bool, i64)> = s.iter().zip(q).map(|(&b, &n)| (b != 0, n)).collect();
    guard(|| trading_checked::run_orders(limit, initial, &os), out)
}

/// # Safety
/// `px` must be valid for `len` elements; `out` must be a valid `*mut i64`.
#[no_mangle]
pub unsafe extern "C" fn rocq_max_drawdown(px: *const i64, len: usize, out: *mut i64) -> i32 {
    let Some(xs) = as_slice(px, len) else {
        return ROCQ_ERR_NULL;
    };
    guard(|| trading::max_drawdown(xs), out)
}

/// Orders are two parallel arrays: `sides[i] != 0` means buy.
///
/// # Safety
/// `sides` and `qtys` must each be valid for `len` elements.
#[no_mangle]
pub unsafe extern "C" fn rocq_run_orders(
    limit: i64,
    initial: i64,
    sides: *const u8,
    qtys: *const i64,
    len: usize,
    out: *mut i64,
) -> i32 {
    let (Some(s), Some(q)) = (as_slice(sides, len), as_slice(qtys, len)) else {
        return ROCQ_ERR_NULL;
    };
    let os: Vec<(bool, i64)> = s.iter().zip(q).map(|(&b, &n)| (b != 0, n)).collect();
    guard(|| trading::run_orders(limit, initial, &os), out)
}

/// All three analytics in one call. `out` must have room for 3 `i64`s:
/// `[max_profit, max_drawdown, final_position]`.
///
/// # Safety
/// `px`/`sides`/`qtys` must be valid for their lengths; `out` for 3 elements.
#[no_mangle]
pub unsafe extern "C" fn rocq_analyze(
    px: *const i64,
    px_len: usize,
    limit: i64,
    sides: *const u8,
    qtys: *const i64,
    os_len: usize,
    out: *mut i64,
) -> i32 {
    let Some(xs) = as_slice(px, px_len) else {
        return ROCQ_ERR_NULL;
    };
    let (Some(s), Some(q)) = (as_slice(sides, os_len), as_slice(qtys, os_len)) else {
        return ROCQ_ERR_NULL;
    };
    if out.is_null() {
        return ROCQ_ERR_NULL;
    }
    let os: Vec<(bool, i64)> = s.iter().zip(q).map(|(&b, &n)| (b != 0, n)).collect();
    quiet_panics();
    match catch_unwind(AssertUnwindSafe(|| trading::analyze(xs, limit, &os))) {
        Ok((profit, dd, pos)) => {
            *out.add(0) = profit;
            *out.add(1) = dd;
            *out.add(2) = pos;
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}
