//! C ABI over the Rocq-extracted algorithms, for `ctypes` and friends.
//!
//! `src/sorting.rs` and `src/trading.rs` are generated by the Makefile:
//! extracted Rocq output plus a small `pub` API suffix. Each keeps its own
//! `Program`, arena and datatypes, so they live in separate modules -- the
//! generated code declares identically-named types in both.
//!
//! Conventions:
//!   - every function returns a status code; results come back via `*mut`
//!     out-parameters, so failure is distinguishable from a valid result
//!   - a zero `len` is always valid, whatever the pointer is
//!   - unwinding is caught at the boundary, never allowed to cross it

mod drive_fsm;
mod energy_fsm;
mod fusion;
mod modexp;
mod mpc;
mod order_fsm;
mod pid;
mod rle;
mod scene;
mod scene_world;
mod sorting;
mod thermo;
mod trading;
/// Same Rocq source, extracted with `ExtrRustCheckedArith`: every `Z`
/// operation becomes `checked_*().unwrap()`, so i64 overflow panics instead
/// of wrapping silently. `catch_unwind` below turns that into `ROCQ_ERR_PANIC`.
mod trading_checked;

use std::panic::{catch_unwind, AssertUnwindSafe};
use std::slice;

pub const ROCQ_OK: i32 = 0;
/// A required pointer was null (with a non-zero length).
pub const ROCQ_ERR_NULL: i32 = -1;
/// The extracted code panicked; the panic was contained.
pub const ROCQ_ERR_PANIC: i32 = -2;

/// # Safety
/// `ptr` must be valid for `len` reads of `T`, or `len` must be 0.
unsafe fn as_slice<'a, T>(ptr: *const T, len: usize) -> Option<&'a [T]> {
    if len == 0 {
        Some(&[])
    } else if ptr.is_null() {
        None
    } else {
        Some(slice::from_raw_parts(ptr, len))
    }
}

/// A library should not write to the caller's stderr. Overflow in the
/// checked build is reported through the return code; set `ROCQ_FFI_VERBOSE`
/// to get Rust's default panic message back for debugging.
fn quiet_panics() {
    use std::sync::Once;
    static ONCE: Once = Once::new();
    ONCE.call_once(|| {
        if std::env::var_os("ROCQ_FFI_VERBOSE").is_none() {
            let default = std::panic::take_hook();
            std::panic::set_hook(Box::new(move |info| {
                if std::env::var_os("ROCQ_FFI_VERBOSE").is_some() {
                    default(info);
                }
            }));
        }
    });
}

fn guard<F: FnOnce() -> i64>(f: F, out: *mut i64) -> i32 {
    quiet_panics();
    if out.is_null() {
        return ROCQ_ERR_NULL;
    }
    match catch_unwind(AssertUnwindSafe(f)) {
        Ok(v) => {
            unsafe { *out = v };
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}

/// Sort `len` values from `input` into `out`, which must have room for `len`.
///
/// # Safety
/// `input` and `out` must each be valid for `len` elements.
#[no_mangle]
pub unsafe extern "C" fn rocq_sort_i64(input: *const i64, len: usize, out: *mut i64) -> i32 {
    let Some(xs) = as_slice(input, len) else {
        return ROCQ_ERR_NULL;
    };
    if len > 0 && out.is_null() {
        return ROCQ_ERR_NULL;
    }
    quiet_panics();
    match catch_unwind(AssertUnwindSafe(|| sorting::sort(xs))) {
        Ok(v) => {
            // v.len() == len is the `insertion_sort_length` theorem, but the
            // FFI boundary does not get to assume Rocq theorems about code it
            // was handed -- clamp anyway.
            let n = v.len().min(len);
            if n > 0 {
                std::ptr::copy_nonoverlapping(v.as_ptr(), out, n);
            }
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}

/// # Safety
/// `px` must be valid for `len` elements; `out` must be a valid `*mut i64`.
#[no_mangle]
pub unsafe extern "C" fn rocq_max_profit(px: *const i64, len: usize, out: *mut i64) -> i32 {
    let Some(xs) = as_slice(px, len) else {
        return ROCQ_ERR_NULL;
    };
    guard(|| trading::max_profit(xs), out)
}

/// Overflow-checked `max_profit`: returns `ROCQ_ERR_PANIC` rather than a
/// wrong answer when an intermediate leaves i64.
///
/// # Safety
/// `px` must be valid for `len` elements; `out` must be a valid `*mut i64`.
#[no_mangle]
pub unsafe extern "C" fn rocq_max_profit_checked(
    px: *const i64,
    len: usize,
    out: *mut i64,
) -> i32 {
    let Some(xs) = as_slice(px, len) else {
        return ROCQ_ERR_NULL;
    };
    guard(|| trading_checked::max_profit(xs), out)
}

/// Overflow-checked `max_drawdown`.
///
/// # Safety
/// `px` must be valid for `len` elements; `out` must be a valid `*mut i64`.
#[no_mangle]
pub unsafe extern "C" fn rocq_max_drawdown_checked(
    px: *const i64,
    len: usize,
    out: *mut i64,
) -> i32 {
    let Some(xs) = as_slice(px, len) else {
        return ROCQ_ERR_NULL;
    };
    guard(|| trading_checked::max_drawdown(xs), out)
}

/// Overflow-checked risk gate.
///
/// # Safety
/// `sides` and `qtys` must each be valid for `len` elements.
#[no_mangle]
pub unsafe extern "C" fn rocq_run_orders_checked(
    limit: i64,
    initial: i64,
    sides: *const u8,
    qtys: *const i64,
    len: usize,
    out: *mut i64,
) -> i32 {
    let (Some(s), Some(q)) = (as_slice(sides, len), as_slice(qtys, len)) else {
        return ROCQ_ERR_NULL;
    };
    let os: Vec<(bool, i64)> = s.iter().zip(q).map(|(&b, &n)| (b != 0, n)).collect();
    guard(|| trading_checked::run_orders(limit, initial, &os), out)
}

/// # Safety
/// `px` must be valid for `len` elements; `out` must be a valid `*mut i64`.
#[no_mangle]
pub unsafe extern "C" fn rocq_max_drawdown(px: *const i64, len: usize, out: *mut i64) -> i32 {
    let Some(xs) = as_slice(px, len) else {
        return ROCQ_ERR_NULL;
    };
    guard(|| trading::max_drawdown(xs), out)
}

/// Orders are two parallel arrays: `sides[i] != 0` means buy.
///
/// # Safety
/// `sides` and `qtys` must each be valid for `len` elements.
#[no_mangle]
pub unsafe extern "C" fn rocq_run_orders(
    limit: i64,
    initial: i64,
    sides: *const u8,
    qtys: *const i64,
    len: usize,
    out: *mut i64,
) -> i32 {
    let (Some(s), Some(q)) = (as_slice(sides, len), as_slice(qtys, len)) else {
        return ROCQ_ERR_NULL;
    };
    let os: Vec<(bool, i64)> = s.iter().zip(q).map(|(&b, &n)| (b != 0, n)).collect();
    guard(|| trading::run_orders(limit, initial, &os), out)
}

/// All three analytics in one call. `out` must have room for 3 `i64`s:
/// `[max_profit, max_drawdown, final_position]`.
///
/// # Safety
/// `px`/`sides`/`qtys` must be valid for their lengths; `out` for 3 elements.
#[no_mangle]
pub unsafe extern "C" fn rocq_analyze(
    px: *const i64,
    px_len: usize,
    limit: i64,
    sides: *const u8,
    qtys: *const i64,
    os_len: usize,
    out: *mut i64,
) -> i32 {
    let Some(xs) = as_slice(px, px_len) else {
        return ROCQ_ERR_NULL;
    };
    let (Some(s), Some(q)) = (as_slice(sides, os_len), as_slice(qtys, os_len)) else {
        return ROCQ_ERR_NULL;
    };
    if out.is_null() {
        return ROCQ_ERR_NULL;
    }
    let os: Vec<(bool, i64)> = s.iter().zip(q).map(|(&b, &n)| (b != 0, n)).collect();
    quiet_panics();
    match catch_unwind(AssertUnwindSafe(|| trading::analyze(xs, limit, &os))) {
        Ok((profit, dd, pos)) => {
            *out.add(0) = profit;
            *out.add(1) = dd;
            *out.add(2) = pos;
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}

/* ================= RLE codec ================= */

/// Run-length encode `len` values. `out_vals`/`out_counts` must have room
/// for `len` entries — sufficient by `encode_length_le`. Writes the number
/// of runs to `out_n`.
///
/// # Safety
/// `input` valid for `len` reads; `out_vals`/`out_counts` valid for `len`
/// writes; `out_n` a valid pointer.
#[no_mangle]
pub unsafe extern "C" fn rocq_rle_encode(
    input: *const i64,
    len: usize,
    out_vals: *mut i64,
    out_counts: *mut u64,
    out_n: *mut usize,
) -> i32 {
    let Some(xs) = as_slice(input, len) else {
        return ROCQ_ERR_NULL;
    };
    if out_n.is_null() || (len > 0 && (out_vals.is_null() || out_counts.is_null())) {
        return ROCQ_ERR_NULL;
    }
    quiet_panics();
    match catch_unwind(AssertUnwindSafe(|| rle::encode(xs))) {
        Ok(v) => {
            let n = v.len().min(len); // == v.len() by encode_length_le; clamp anyway
            for (i, (val, cnt)) in v.into_iter().take(n).enumerate() {
                *out_vals.add(i) = val;
                *out_counts.add(i) = cnt;
            }
            *out_n = n;
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}

/// Returned by `rocq_rle_decode` when the decoded output exceeds `out_cap`.
pub const ROCQ_ERR_CAPACITY: i32 = -3;

/// Decode `n` (value, count) runs into `out` (capacity `out_cap`); writes
/// the decoded length to `out_len`.
///
/// # Safety
/// `vals`/`counts` valid for `n` reads; `out` valid for `out_cap` writes;
/// `out_len` a valid pointer.
#[no_mangle]
pub unsafe extern "C" fn rocq_rle_decode(
    vals: *const i64,
    counts: *const u64,
    n: usize,
    out: *mut i64,
    out_cap: usize,
    out_len: *mut usize,
) -> i32 {
    let (Some(vs), Some(cs)) = (as_slice(vals, n), as_slice(counts, n)) else {
        return ROCQ_ERR_NULL;
    };
    if out_len.is_null() || (out_cap > 0 && out.is_null()) {
        return ROCQ_ERR_NULL;
    }
    let pairs: Vec<(i64, u64)> = vs.iter().zip(cs).map(|(&v, &c)| (v, c)).collect();
    quiet_panics();
    match catch_unwind(AssertUnwindSafe(|| rle::decode(&pairs))) {
        Ok(v) => {
            if v.len() > out_cap {
                return ROCQ_ERR_CAPACITY;
            }
            if !v.is_empty() {
                std::ptr::copy_nonoverlapping(v.as_ptr(), out, v.len());
            }
            *out_len = v.len();
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}

/* ================= modular exponentiation ================= */

/// `(b ^ e) mod m` (`pow_mod_correct`). Checked build: panics (contained,
/// `ROCQ_ERR_PANIC`) on `m == 0` or intermediates outside u64 — the bindings
/// enforce `1 <= m <= 2^32` (`safe_modulus`) so neither can happen.
///
/// # Safety
/// `out` must be a valid `*mut u64`.
#[no_mangle]
pub unsafe extern "C" fn rocq_pow_mod(m: u64, b: u64, e: u64, out: *mut u64) -> i32 {
    if out.is_null() {
        return ROCQ_ERR_NULL;
    }
    quiet_panics();
    match catch_unwind(AssertUnwindSafe(|| modexp::pow_mod(m, b, e))) {
        Ok(v) => {
            *out = v;
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}

/* ================= order FSM ================= */

/// Run `n` events (`fills[i] != 0` => Fill(qtys[i]), else Cancel) against a
/// fresh order of size `qty`. Writes final fill to `out_filled` and cancel
/// flag to `out_canceled`. Safe for all event streams (`run_invariant`,
/// `fill_add_bounded`); negative/overfilling fills are rejected in-machine.
///
/// # Safety
/// `fills`/`qtys` valid for `n` reads; out pointers valid.
#[no_mangle]
pub unsafe extern "C" fn rocq_order_fsm_run(
    qty: i64,
    fills: *const u8,
    qtys: *const i64,
    n: usize,
    out_filled: *mut i64,
    out_canceled: *mut u8,
) -> i32 {
    let (Some(fs), Some(qs)) = (as_slice(fills, n), as_slice(qtys, n)) else {
        return ROCQ_ERR_NULL;
    };
    if out_filled.is_null() || out_canceled.is_null() {
        return ROCQ_ERR_NULL;
    }
    let evs: Vec<(bool, i64)> = fs.iter().zip(qs).map(|(&f, &q)| (f != 0, q)).collect();
    quiet_panics();
    match catch_unwind(AssertUnwindSafe(|| order_fsm::run(qty, &evs))) {
        Ok((filled, canceled)) => {
            *out_filled = filled;
            *out_canceled = canceled as u8;
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}

/* ================= drive-mode FSM ================= */

/// Run shift/fault events from Park. Events as parallel arrays:
/// `tags[i]` 0=shift 1=fault 2=clear; `gears[i]` 0=P 1=R 2=N 3=D (shift
/// only); `speeds[i]` cm/s. Final mode (0..=4, 4=Fault) to `out_mode`.
/// Interlocks proved: park/reverse/drive engage gates, fault absorbing
/// (DriveModeFsm.v). No arithmetic on speeds — any i64 is safe.
///
/// # Safety
/// `tags`/`gears`/`speeds` valid for `n` reads; `out_mode` valid.
#[no_mangle]
pub unsafe extern "C" fn rocq_drive_fsm_run(
    tags: *const u8,
    gears: *const u8,
    speeds: *const i64,
    n: usize,
    out_mode: *mut u8,
) -> i32 {
    let (Some(t), Some(g), Some(v)) =
        (as_slice(tags, n), as_slice(gears, n), as_slice(speeds, n))
    else {
        return ROCQ_ERR_NULL;
    };
    if out_mode.is_null() {
        return ROCQ_ERR_NULL;
    }
    let evs: Vec<(u8, u8, i64)> =
        t.iter().zip(g).zip(v).map(|((&a, &b), &c)| (a, b, c)).collect();
    quiet_panics();
    match catch_unwind(AssertUnwindSafe(|| drive_fsm::run(&evs))) {
        Ok(m) => {
            *out_mode = m;
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}

/* ================= hybrid energy FSM ================= */

/// Run power requests from initial SoC (per-mille, clamped into [0,1000]).
/// Outputs final mode (0=EV 1=HybridAssist 2=ChargeSustain) and SoC.
/// Proved: SoC bounds and the EV floor hold for EVERY request stream
/// (HybridEnergyFsm.v) — no domain to enforce.
///
/// # Safety
/// `reqs` valid for `n` reads; out pointers valid.
#[no_mangle]
pub unsafe extern "C" fn rocq_energy_fsm_run(
    soc0: i64,
    reqs: *const i64,
    n: usize,
    out_mode: *mut u8,
    out_soc: *mut i64,
) -> i32 {
    let Some(rs) = as_slice(reqs, n) else {
        return ROCQ_ERR_NULL;
    };
    if out_mode.is_null() || out_soc.is_null() {
        return ROCQ_ERR_NULL;
    }
    quiet_panics();
    match catch_unwind(AssertUnwindSafe(|| energy_fsm::run(soc0, rs))) {
        Ok((m, soc)) => {
            *out_mode = m;
            *out_soc = soc;
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}

/* ================= PID ================= */

/// Run the PID over `n` errors from the zero state; writes `n` outputs.
/// Proved: every output in [-U_MAX, U_MAX] and the integral clamped, for
/// ALL inputs; intermediates fit i64 for |gains| <= 2^15, |errors| <= 2^31
/// (Pid.v) — the bindings enforce the latter.
///
/// # Safety
/// `errors` valid for `n` reads; `out_us` valid for `n` writes; out
/// pointers valid.
#[no_mangle]
pub unsafe extern "C" fn rocq_pid_run(
    kp: i64,
    ki: i64,
    kd: i64,
    errors: *const i64,
    n: usize,
    out_us: *mut i64,
    out_integ: *mut i64,
    out_prev: *mut i64,
) -> i32 {
    let Some(es) = as_slice(errors, n) else {
        return ROCQ_ERR_NULL;
    };
    if (n > 0 && out_us.is_null()) || out_integ.is_null() || out_prev.is_null() {
        return ROCQ_ERR_NULL;
    }
    quiet_panics();
    match catch_unwind(AssertUnwindSafe(|| pid::run(kp, ki, kd, es))) {
        Ok((us, integ, prev)) => {
            let m = us.len().min(n);
            if m > 0 {
                std::ptr::copy_nonoverlapping(us.as_ptr(), out_us, m);
            }
            *out_integ = integ;
            *out_prev = prev;
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}

/* ================= hysteresis thermostat ================= */

/// Closed-loop thermostat from `t0` (heater off) under per-step
/// disturbance rates (clamped in-machine to [1, RMAX]). Proved: band
/// invariance, no chattering, strict progress (Hysteresis.v); i64 safety
/// for |t0| <= 2^62 — enforced by the bindings.
///
/// # Safety
/// `rhs`/`rcs` valid for `n` reads; out pointers valid.
#[no_mangle]
pub unsafe extern "C" fn rocq_thermo_run(
    t0: i64,
    rhs: *const i64,
    rcs: *const i64,
    n: usize,
    out_t: *mut i64,
    out_heating: *mut u8,
) -> i32 {
    let (Some(rh), Some(rc)) = (as_slice(rhs, n), as_slice(rcs, n)) else {
        return ROCQ_ERR_NULL;
    };
    if out_t.is_null() || out_heating.is_null() {
        return ROCQ_ERR_NULL;
    }
    let ds: Vec<(i64, i64)> = rh.iter().zip(rc).map(|(&a, &b)| (a, b)).collect();
    quiet_panics();
    match catch_unwind(AssertUnwindSafe(|| thermo::run(t0, &ds))) {
        Ok((t, h)) => {
            *out_t = t;
            *out_heating = h as u8;
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}

/* ================= finite-set MPC ================= */

/// One receding-horizon decision: minimize accumulated tracking cost over
/// the depth-`horizon` action tree. Writes predicted cost and the first
/// action (-1/0/+1). Proved optimal over the enumerated set (mpc_le_all,
/// mpc_realizable in Mpc.v); i64-safe for |pos|,|vel|,|ref| <= 2^20 and
/// horizon <= 8 — enforced by the bindings.
///
/// # Safety
/// Out pointers must be valid.
#[no_mangle]
pub unsafe extern "C" fn rocq_mpc_decide(
    reference: i64,
    pos: i64,
    vel: i64,
    horizon: u64,
    out_cost: *mut i64,
    out_action: *mut i8,
) -> i32 {
    if out_cost.is_null() || out_action.is_null() {
        return ROCQ_ERR_NULL;
    }
    quiet_panics();
    match catch_unwind(AssertUnwindSafe(|| mpc::decide(reference, pos, vel, horizon))) {
        Ok((c, a)) => {
            *out_cost = c;
            *out_action = a;
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}

/* ================= sensor fusion ================= */

/// Median-fuse `n` readings and gate each against the fused value with
/// tolerance `tol`. Writes fused value and per-reading flags (0/1).
/// Proved: median is one of the readings, majority-band fault masking,
/// pairwise 2*tol scene consistency (SensorFusion.v — the median uses the
/// verified insertion sort); i64-safe for |values|, tol <= 2^62 - 1 —
/// enforced by the bindings.
///
/// # Safety
/// `readings` valid for `n` reads; `out_flags` valid for `n` writes;
/// `out_fused` valid.
#[no_mangle]
pub unsafe extern "C" fn rocq_fusion_fuse(
    tol: i64,
    readings: *const i64,
    n: usize,
    out_fused: *mut i64,
    out_flags: *mut u8,
) -> i32 {
    let Some(rs) = as_slice(readings, n) else {
        return ROCQ_ERR_NULL;
    };
    if out_fused.is_null() || (n > 0 && out_flags.is_null()) {
        return ROCQ_ERR_NULL;
    }
    quiet_panics();
    match catch_unwind(AssertUnwindSafe(|| fusion::fuse(tol, rs))) {
        Ok((f, flags)) => {
            *out_fused = f;
            for (i, b) in flags.into_iter().take(n).enumerate() {
                *out_flags.add(i) = b as u8;
            }
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}

/* ================= ADAS scene checker ================= */

/// Check a scene: road model + ego speed + `n` objects as parallel arrays
/// (classes: 0 vehicle, 1 pedestrian, 2 bicycle, 3 sign, 4 light; tl
/// states: 0 none, 1 red, 2 yellow, 3 green). Writes per-object verdicts
/// (0 confirmed / 1 low / 2 implausible), scores and rule masks, plus the
/// scene-level validity flag.
///
/// Total for ANY inputs (validate-then-compute architecture:
/// validated_bounds + pair_arith_fits in SceneModel.v) — there is no
/// domain for the caller to respect.
///
/// # Safety
/// All input arrays valid for `n` reads; all output arrays valid for `n`
/// writes; scalar out pointers valid.
#[no_mangle]
pub unsafe extern "C" fn rocq_scene_check(
    lanes: i64, lane_w: i64, curv: i64, limit: i64,
    ego_v: i64,
    classes: *const u8,
    xs: *const i64, ys: *const i64,
    vxs: *const i64, vys: *const i64,
    ws: *const i64, ls: *const i64,
    confs: *const i64,
    targets: *const u8,
    tls: *const i64,
    n: usize,
    out_scene_ok: *mut u8,
    out_verdicts: *mut u8,
    out_scores: *mut i64,
    out_masks: *mut i64,
) -> i32 {
    let (Some(cl), Some(x), Some(y), Some(vx), Some(vy), Some(w), Some(l),
         Some(cf), Some(tg), Some(tl)) =
        (as_slice(classes, n), as_slice(xs, n), as_slice(ys, n),
         as_slice(vxs, n), as_slice(vys, n), as_slice(ws, n),
         as_slice(ls, n), as_slice(confs, n), as_slice(targets, n),
         as_slice(tls, n))
    else {
        return ROCQ_ERR_NULL;
    };
    if out_scene_ok.is_null()
        || (n > 0
            && (out_verdicts.is_null() || out_scores.is_null()
                || out_masks.is_null()))
    {
        return ROCQ_ERR_NULL;
    }
    let objs: Vec<scene::SceneObj> = (0..n)
        .map(|i| scene::SceneObj {
            class: cl[i], x: x[i], y: y[i], vx: vx[i], vy: vy[i],
            w: w[i], l: l[i], conf: cf[i], target: tg[i] != 0, tl: tl[i],
        })
        .collect();
    quiet_panics();
    match catch_unwind(AssertUnwindSafe(|| {
        scene::check(lanes, lane_w, curv, limit, ego_v, &objs)
    })) {
        Ok((ok, entries)) => {
            *out_scene_ok = ok as u8;
            for (i, (v, sc, mask)) in entries.into_iter().take(n).enumerate() {
                *out_verdicts.add(i) = v;
                *out_scores.add(i) = sc;
                *out_masks.add(i) = mask;
            }
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}

/* ================= world-frame scene checker ================= */

/// Like `rocq_scene_check`, but objects are in WORLD coordinates and an
/// ego pose (px, py, heading in quarter-turns CCW, world velocity) is
/// supplied; the verified code ingests (translate + rotate) before
/// checking. UNLIKE the ego-frame checker this has a caller domain:
/// |coordinates|, |velocities|, |pose| <= 2^62 - 1 (`SAFE_COORD`,
/// `ingest_fits_i64` in SceneWorld.v). Outside it the checked build
/// panics — contained here as `ROCQ_ERR_PANIC`, never silent.
///
/// # Safety
/// All input arrays valid for `n` reads; all output arrays valid for `n`
/// writes; scalar out pointers valid.
#[no_mangle]
pub unsafe extern "C" fn rocq_scene_world_check(
    lanes: i64, lane_w: i64, curv: i64, limit: i64,
    px: i64, py: i64, ph: i64, pvx: i64, pvy: i64,
    classes: *const u8,
    xs: *const i64, ys: *const i64,
    vxs: *const i64, vys: *const i64,
    ws: *const i64, ls: *const i64,
    confs: *const i64,
    targets: *const u8,
    tls: *const i64,
    n: usize,
    out_scene_ok: *mut u8,
    out_verdicts: *mut u8,
    out_scores: *mut i64,
    out_masks: *mut i64,
) -> i32 {
    let (Some(cl), Some(x), Some(y), Some(vx), Some(vy), Some(w), Some(l),
         Some(cf), Some(tg), Some(tl)) =
        (as_slice(classes, n), as_slice(xs, n), as_slice(ys, n),
         as_slice(vxs, n), as_slice(vys, n), as_slice(ws, n),
         as_slice(ls, n), as_slice(confs, n), as_slice(targets, n),
         as_slice(tls, n))
    else {
        return ROCQ_ERR_NULL;
    };
    if out_scene_ok.is_null()
        || (n > 0
            && (out_verdicts.is_null() || out_scores.is_null()
                || out_masks.is_null()))
    {
        return ROCQ_ERR_NULL;
    }
    let objs: Vec<scene_world::SceneObj> = (0..n)
        .map(|i| scene_world::SceneObj {
            class: cl[i], x: x[i], y: y[i], vx: vx[i], vy: vy[i],
            w: w[i], l: l[i], conf: cf[i], target: tg[i] != 0, tl: tl[i],
        })
        .collect();
    quiet_panics();
    match catch_unwind(AssertUnwindSafe(|| {
        scene_world::check_world(lanes, lane_w, curv, limit,
                                 px, py, ph, pvx, pvy, &objs)
    })) {
        Ok((ok, entries)) => {
            *out_scene_ok = ok as u8;
            for (i, (v, sc, mask)) in entries.into_iter().take(n).enumerate() {
                *out_verdicts.add(i) = v;
                *out_scores.add(i) = sc;
                *out_masks.add(i) = mask;
            }
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}

/// Overflow-checked `rocq_analyze` (same contract; wraps the
/// ExtrRustCheckedArith build so i64 overflow panics instead of wrapping).
///
/// # Safety
/// `px`/`sides`/`qtys` must be valid for their lengths; `out` for 3 elements.
#[no_mangle]
pub unsafe extern "C" fn rocq_analyze_checked(
    px: *const i64,
    px_len: usize,
    limit: i64,
    sides: *const u8,
    qtys: *const i64,
    os_len: usize,
    out: *mut i64,
) -> i32 {
    let Some(xs) = as_slice(px, px_len) else {
        return ROCQ_ERR_NULL;
    };
    let (Some(s), Some(q)) = (as_slice(sides, os_len), as_slice(qtys, os_len)) else {
        return ROCQ_ERR_NULL;
    };
    if out.is_null() {
        return ROCQ_ERR_NULL;
    }
    let os: Vec<(bool, i64)> = s.iter().zip(q).map(|(&b, &n)| (b != 0, n)).collect();
    quiet_panics();
    match catch_unwind(AssertUnwindSafe(|| trading_checked::analyze(xs, limit, &os))) {
        Ok((profit, dd, pos)) => {
            *out.add(0) = profit;
            *out.add(1) = dd;
            *out.add(2) = pos;
            ROCQ_OK
        }
        Err(_) => ROCQ_ERR_PANIC,
    }
}
