(** * Verified insertion sort, extracted to Rust

    We define insertion sort over [list Z], prove two theorems about it

      - [insertion_sort_sorted] : the output is sorted
      - [insertion_sort_perm]   : the output is a permutation of the input

    and then extract the *proved* function to Rust.  The Rust code is
    generated by [rocq-rust-extraction] (AU-COBRA), which runs MetaRocq's
    verified typed erasure inside Rocq and pretty-prints the resulting
    lambda-box term as Rust. *)

From Stdlib Require Import List.
From Stdlib Require Import ZArith.
From Stdlib Require Import Sorted.
From Stdlib Require Import Permutation.
From Stdlib Require Import Lia.

Import ListNotations.
Local Open Scope Z_scope.

(** ** The program *)

(** Insert [x] into an already-sorted list, keeping it sorted. *)
Fixpoint insert (x : Z) (l : list Z) : list Z :=
  match l with
  | [] => [x]
  | y :: l' => if x <=? y then x :: y :: l' else y :: insert x l'
  end.

Fixpoint insertion_sort (l : list Z) : list Z :=
  match l with
  | [] => []
  | x :: l' => insert x (insertion_sort l')
  end.

(** ** Proof that the result is sorted *)

Local Notation Sorted := (Sorted Z.le).
Local Notation HdRel := (HdRel Z.le).

Lemma insert_hdrel : forall x y l,
  y <= x -> HdRel y l -> HdRel y (insert x l).
Proof.
  intros x y l Hyx Hrel.
  destruct l as [| z l']; simpl.
  - now constructor.
  - inversion Hrel; subst.
    destruct (x <=? z); constructor; assumption.
Qed.

Lemma insert_sorted : forall x l, Sorted l -> Sorted (insert x l).
Proof.
  intros x l H. induction H as [| y l' Hsorted IH Hrel]; simpl.
  - now repeat constructor.
  - destruct (x <=? y) eqn:Hxy.
    + apply Z.leb_le in Hxy.
      constructor.
      * constructor; assumption.
      * constructor; assumption.
    + apply Z.leb_gt in Hxy.
      constructor; [assumption |].
      apply insert_hdrel; [lia | assumption].
Qed.

Theorem insertion_sort_sorted : forall l, Sorted (insertion_sort l).
Proof.
  induction l as [| x l' IH]; simpl.
  - constructor.
  - now apply insert_sorted.
Qed.

(** ** Proof that the result is a permutation of the input *)

Lemma insert_perm : forall x l, Permutation (x :: l) (insert x l).
Proof.
  intros x l. induction l as [| y l' IH]; simpl.
  - reflexivity.
  - destruct (x <=? y).
    + reflexivity.
    + transitivity (y :: x :: l').
      * constructor.
      * now constructor.
Qed.

Theorem insertion_sort_perm : forall l, Permutation l (insertion_sort l).
Proof.
  induction l as [| x l' IH]; simpl.
  - reflexivity.
  - transitivity (x :: insertion_sort l').
    + now constructor.
    + apply insert_perm.
Qed.

(** ** Bonus: the sort is idempotent on its own output, as a sanity check. *)

Theorem insertion_sort_length : forall l,
  length (insertion_sort l) = length l.
Proof.
  intros l. symmetry. apply Permutation_length, insertion_sort_perm.
Qed.

(** ** The entry point we extract

    A closed term, so the generated Rust [main] needs no list building:
    it just calls [demo] and prints the (verified-sorted) result. *)

Definition sample : list Z := [5; 3; 8; 1; 9; 2; 7; -4; 0; 6].

Definition demo : list Z := insertion_sort sample.

(** The result is computed and checked here, inside Rocq, so we know what
    the Rust binary must print. *)
Example demo_value : demo = [-4; 0; 1; 2; 3; 5; 6; 7; 8; 9].
Proof. vm_compute. reflexivity. Qed.
