
/* ------------------------------------------------------------------ *
 * Hand-written driver.  Everything above this line was generated by   *
 * MetaRocq's verified erasure from theories/InsertionSort.v.          *
 * Nothing below is verified -- it only marshals values across the     *
 * boundary and re-checks the two theorems at runtime.                 *
 * ------------------------------------------------------------------ */

type ZList<'a> = Corelib_Init_Datatypes_list<'a, i64>;

/// Extracted cons-list -> Vec<i64>.
fn to_vec<'a>(mut l: &'a ZList<'a>) -> Vec<i64> {
    let mut v = Vec::new();
    loop {
        match l {
            Corelib_Init_Datatypes_list::nil(_) => return v,
            Corelib_Init_Datatypes_list::cons(_, x, rest) => {
                v.push(*x);
                l = *rest;
            }
        }
    }
}

/// &[i64] -> extracted cons-list, allocated in the program's bump arena.
fn from_slice<'a>(p: &'a Program, xs: &[i64]) -> &'a ZList<'a> {
    let mut acc: &'a ZList<'a> = p.alloc(Corelib_Init_Datatypes_list::nil(PhantomData));
    for &x in xs.iter().rev() {
        acc = p.alloc(Corelib_Init_Datatypes_list::cons(PhantomData, x, acc));
    }
    acc
}

/// Runtime counterpart of `insertion_sort_sorted`.
fn is_sorted(v: &[i64]) -> bool {
    v.windows(2).all(|w| w[0] <= w[1])
}

/// Runtime counterpart of `insertion_sort_perm`.
fn is_permutation(a: &[i64], b: &[i64]) -> bool {
    let (mut a, mut b) = (a.to_vec(), b.to_vec());
    a.sort_unstable();
    b.sort_unstable();
    a == b
}

fn check(label: &str, input: &[i64], output: &[i64]) {
    let sorted = is_sorted(output);
    let perm = is_permutation(input, output);
    println!("  {:<22} sorted={:<5} permutation={:<5} len={}", label, sorted, perm, output.len());
    assert!(sorted, "{}: output not sorted", label);
    assert!(perm, "{}: output not a permutation of input", label);
}

fn main() {
    let p = Program::new();

    println!("=== Extracted from Rocq: insertion_sort (proved sorted + permutation) ===\n");

    // 1. The closed `demo` term from the Rocq file.
    let input = to_vec(p.RocqRustExamples_InsertionSort_sample());
    let output = to_vec(p.RocqRustExamples_InsertionSort_demo());
    println!("demo (from theories/InsertionSort.v)");
    println!("  input  : {:?}", input);
    println!("  output : {:?}", output);
    println!("  Rocq proved this equals [-4; 0; 1; 2; 3; 5; 6; 7; 8; 9] (Example demo_value)");
    assert_eq!(output, vec![-4, 0, 1, 2, 3, 5, 6, 7, 8, 9]);
    println!("  matches Rocq's vm_compute result: true\n");

    // 2. Call the extracted function on data built in Rust.
    println!("calling the extracted insertion_sort on Rust-built inputs");
    let cases: Vec<Vec<i64>> = vec![
        vec![],
        vec![42],
        vec![3, 1, 2],
        vec![5, 4, 3, 2, 1],
        vec![1, 2, 3, 4, 5],
        vec![7, 7, 7, -1, -1, 0],
        vec![i64::MAX, i64::MIN, 0, -1, 1],
    ];
    for c in &cases {
        let got = to_vec(p.RocqRustExamples_InsertionSort_insertion_sort(from_slice(&p, c)));
        println!("  {:?} -> {:?}", c, got);
        check("case", c, &got);
    }

    // 3. A larger deterministic pseudo-random input.
    let mut seed: u64 = 0x2545_F491_4F6C_DD1D;
    let big: Vec<i64> = (0..1000)
        .map(|_| {
            seed ^= seed << 13;
            seed ^= seed >> 7;
            seed ^= seed << 17;
            (seed % 20001) as i64 - 10000
        })
        .collect();
    let big_sorted = to_vec(p.RocqRustExamples_InsertionSort_insertion_sort(from_slice(&p, &big)));
    println!("\n1000 pseudo-random values in [-10000, 10000]");
    println!("  first 10 in : {:?}", &big[..10]);
    println!("  first 10 out: {:?}", &big_sorted[..10]);
    println!("  last  10 out: {:?}", &big_sorted[big_sorted.len() - 10..]);
    check("1000 random", &big, &big_sorted);

    println!("\nAll runtime checks passed.");
}
