
/* ------------------------------------------------------------------ *
 * Hand-written driver.  Everything above was generated by MetaRocq's  *
 * verified erasure from theories/Trading.v.  Nothing below is          *
 * verified: it marshals values and runs a differential test of the    *
 * extracted O(n) algorithms against naive O(n^2) transliterations of  *
 * the Rocq specifications -- i.e. a runtime witness of the theorems.  *
 * ------------------------------------------------------------------ */

type Prices<'a> = Corelib_Init_Datatypes_list<'a, i64>;
type Order<'a> = RocqRustExamples_Trading_order<'a>;
type Orders<'a> = Corelib_Init_Datatypes_list<'a, &'a Order<'a>>;

fn prices_from<'a>(p: &'a Program, xs: &[i64]) -> &'a Prices<'a> {
    let mut acc: &'a Prices<'a> = p.alloc(Corelib_Init_Datatypes_list::nil(PhantomData));
    for &x in xs.iter().rev() {
        acc = p.alloc(Corelib_Init_Datatypes_list::cons(PhantomData, x, acc));
    }
    acc
}

fn orders_from<'a>(p: &'a Program, os: &[(bool, i64)]) -> &'a Orders<'a> {
    let mut acc: &'a Orders<'a> = p.alloc(Corelib_Init_Datatypes_list::nil(PhantomData));
    for &(buy, qty) in os.iter().rev() {
        let o: &'a Order<'a> = p.alloc(Order::mkOrder(PhantomData, buy, qty));
        acc = p.alloc(Corelib_Init_Datatypes_list::cons(PhantomData, o, acc));
    }
    acc
}

fn unpack(a: &RocqRustExamples_Trading_analytics) -> (i64, i64, i64) {
    match a {
        RocqRustExamples_Trading_analytics::mkAnalytics(_, profit, dd, pos) => (*profit, *dd, *pos),
    }
}

/* ---- naive transliterations of the Rocq *specifications* ---- */

/// max over i < j of (p[j] - p[i]), 0 if no trade beats doing nothing.
fn max_profit_naive(p: &[i64]) -> i64 {
    let mut best = 0;
    for i in 0..p.len() {
        for j in (i + 1)..p.len() {
            best = best.max(p[j] - p[i]);
        }
    }
    best
}

/// max over i < j of (p[i] - p[j]) -- peak before trough.
fn max_drawdown_naive(p: &[i64]) -> i64 {
    let mut worst = 0;
    for i in 0..p.len() {
        for j in (i + 1)..p.len() {
            worst = worst.max(p[i] - p[j]);
        }
    }
    worst
}

fn run_orders_naive(lim: i64, mut pos: i64, os: &[(bool, i64)]) -> i64 {
    for &(buy, qty) in os {
        let want = if buy { pos + qty } else { pos - qty };
        if -lim <= want && want <= lim {
            pos = want;
        }
    }
    pos
}

struct Rng(u64);
impl Rng {
    fn next(&mut self) -> u64 {
        self.0 ^= self.0 << 13;
        self.0 ^= self.0 >> 7;
        self.0 ^= self.0 << 17;
        self.0
    }
    fn range(&mut self, lo: i64, hi: i64) -> i64 {
        lo + (self.next() % ((hi - lo + 1) as u64)) as i64
    }
}

fn main() {
    let p = Program::new();

    println!("=== Verified trading analytics, extracted from Rocq ===\n");

    /* ---- 1. A worked example ---- */

    // A price path in cents.
    let path: Vec<i64> = vec![
        10_000, 10_240, 9_870, 9_610, 10_120, 10_890, 11_450, 10_980, 9_940, 9_320,
        9_780, 10_310, 11_020, 11_890, 11_400, 11_960,
    ];
    // Orders: (is_buy, qty).  Limit is 100 shares; several of these breach it
    // and must be rejected by the gate.
    let limit: i64 = 100;
    let orders: Vec<(bool, i64)> = vec![
        (true, 60),    // 0   -> 60
        (true, 60),    // 120 breaches, rejected -> 60
        (true, 40),    // -> 100
        (true, 1),     // 101 breaches, rejected -> 100
        (false, 250),  // -150 breaches, rejected -> 100
        (false, 180),  // -80  ok -> -80
        (false, 30),   // -110 breaches, rejected -> -80
        (true, 500),   // 420 breaches, rejected -> -80
    ];

    let a = p.RocqRustExamples_Trading_analyze(
        prices_from(&p, &path),
        limit,
        orders_from(&p, &orders),
    );
    let (profit, dd, pos) = unpack(a);

    println!("price path ({} points, cents):", path.len());
    println!("  {:?}", path);
    println!("  low {}  high {}", path.iter().min().unwrap(), path.iter().max().unwrap());
    println!();
    println!("  max_profit    = {:>6}   (buy {} sell {})", profit, 9_320, 11_960);
    println!("  max_drawdown  = {:>6}   (peak 11450 -> trough 9320)", dd);
    println!();
    println!("risk gate, position limit +/-{}:", limit);
    let mut sim = 0i64;
    for (i, &(buy, qty)) in orders.iter().enumerate() {
        let want = if buy { sim + qty } else { sim - qty };
        let ok = -limit <= want && want <= limit;
        if ok {
            sim = want;
        }
        println!(
            "  {:>2}. {} {:>4}  want {:>5}  {}  position {:>5}",
            i + 1,
            if buy { "BUY " } else { "SELL" },
            qty,
            want,
            if ok { "accept" } else { "REJECT" },
            sim
        );
    }
    println!("  final position = {}", pos);
    assert_eq!(pos, sim);

    /* ---- 2. Differential test: extracted O(n) vs naive O(n^2) spec ---- */

    println!("\n=== differential test vs the naive O(n^2) specifications ===\n");
    let mut rng = Rng(0x9E37_79B9_7F4A_7C15);
    let trials = 5_000;
    let mut checked_prices = 0usize;

    for _ in 0..trials {
        let n = (rng.next() % 41) as usize; // 0..=40 points
        let series: Vec<i64> = (0..n).map(|_| rng.range(-50_000, 50_000)).collect();

        let got_profit = p.RocqRustExamples_Trading_max_profit(prices_from(&p, &series));
        let got_dd = p.RocqRustExamples_Trading_max_drawdown(prices_from(&p, &series));

        assert_eq!(got_profit, max_profit_naive(&series), "max_profit mismatch on {:?}", series);
        assert_eq!(got_dd, max_drawdown_naive(&series), "max_drawdown mismatch on {:?}", series);
        assert!(got_profit >= 0 && got_dd >= 0);
        checked_prices += 1;
    }
    println!("  max_profit_correct    : {} random series agree with the spec", checked_prices);
    println!("  max_drawdown_correct  : {} random series agree with the spec", checked_prices);
    println!("  ..._nonneg            : held on all {} series", checked_prices);

    /* ---- 3. Risk gate stress: adversarial orders ---- */

    let mut breaches = 0usize;
    let mut rejected = 0usize;
    let mut total = 0usize;
    for _ in 0..trials {
        // The theorem needs -lim <= 0 <= lim, i.e. lim >= 0.  Honour that.
        let lim = rng.range(0, 1_000);
        let n = (rng.next() % 31) as usize;
        let os: Vec<(bool, i64)> = (0..n)
            .map(|_| (rng.next() % 2 == 0, rng.range(-5_000, 5_000)))
            .collect();

        let got = p.RocqRustExamples_Trading_run_orders(lim, 0, orders_from(&p, &os));
        assert_eq!(got, run_orders_naive(lim, 0, &os));
        if !(-lim <= got && got <= lim) {
            breaches += 1;
        }
        // count how many orders the gate turned away
        let mut sim = 0i64;
        for &(buy, qty) in &os {
            let want = if buy { sim + qty } else { sim - qty };
            total += 1;
            if -lim <= want && want <= lim {
                sim = want;
            } else {
                rejected += 1;
            }
        }
    }
    println!(
        "\n  run_orders_within_limit: {} sequences, {} orders, {} rejected by the gate",
        trials, total, rejected
    );
    println!("  limit breaches observed: {}", breaches);
    assert_eq!(breaches, 0);

    println!("\nAll runtime checks passed.");
}
